# Generated by Django 4.2.26 on 2025-11-27 22:21

from django.db import migrations, models
import django.db.models.deletion
import encomendas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_encomenda', models.CharField(max_length=30)),
                ('codigo_retirada', models.CharField(default=encomendas.models.generate_code, editable=False, max_length=6, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='encomendas_fotos/')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_retirada', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RETIRADA', 'Retirada')], default='PENDENTE', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('REGISTRO', 'Registro de Entrada'), ('RETIRADA', 'Baixa de Retirada'), ('EDICAO', 'Edição de Dados'), ('DELECAO_ADM', 'Deleção Lógica')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='encomendas.encomenda')),
            ],
        ),
    ]
