# Generated by Django 4.2.26 on 2025-11-27 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encomendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmovimentacao',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='funcionario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomendas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='morador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomendas', to='usuarios.morador'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='transportadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encomendas.transportadora'),
        ),
    ]
