# Generated by Django 4.2.26 on 2025-11-30 20:13

from django.db import migrations, models
import encomendas.models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encomenda',
            options={'verbose_name': 'Encomenda', 'verbose_name_plural': 'Encomendas'},
        ),
        migrations.AlterModelOptions(
            name='logmovimentacao',
            options={'verbose_name': 'Log de Movimentação'},
        ),
        migrations.AlterModelOptions(
            name='transportadora',
            options={'verbose_name': 'Transportadora'},
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo (Deleção Lógica)'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='codigo_encomenda',
            field=models.CharField(max_length=30, verbose_name='Código de Rastreio'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='codigo_retirada',
            field=models.CharField(default=encomendas.models.generate_code, editable=False, max_length=6, unique=True, verbose_name='Código de Retirada'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição Visual'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='encomendas_fotos/', verbose_name='Foto/Comprovante'),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='codigo',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Código Identificador'),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
    ]
