# Generated by Django 4.2.26 on 2025-11-27 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='morador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.morador'),
        ),
    ]
